server:
  port: 8080
chatgpt:
  token: Put your token here
mysql:
  ddl: CREATE
  host: localhost:3306
  protocol: tcp
  schema: name_gpt
  user: root
  password: test
  maxIdleConn: 10
  maxOpenConn: 10