// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/domains/recommendations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Generates domain names in server sent event.",
                "parameters": [
                    {
                        "description": "Generate domain name recommendation",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_copolio_namegpt_pkg_dto.RecommendDomainNames"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "domain",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/domains/similar-names": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "Get similar domain names given input",
                "parameters": [
                    {
                        "description": "Generate similar domain name",
                        "name": "q",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_copolio_namegpt_pkg_dto.GenerateDomainNames"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "domain names",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_copolio_namegpt_pkg_dto.GenerateDomainNameResult"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_copolio_namegpt_pkg_dto.DomainInfo": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "suffix": {
                    "type": "string"
                }
            }
        },
        "github_com_copolio_namegpt_pkg_dto.GenerateDomainNameResult": {
            "type": "object",
            "properties": {
                "domainName": {
                    "type": "string"
                },
                "info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_copolio_namegpt_pkg_dto.DomainInfo"
                    }
                }
            }
        },
        "github_com_copolio_namegpt_pkg_dto.GenerateDomainNames": {
            "type": "object",
            "required": [
                "keyword"
            ],
            "properties": {
                "keyword": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "github_com_copolio_namegpt_pkg_dto.RecommendDomainNames": {
            "type": "object",
            "required": [
                "description"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "previousResults": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
