definitions:
  github_com_copolio_namegpt_pkg_dto.DomainInfo:
    properties:
      available:
        type: boolean
      domain:
        type: string
      price:
        type: string
      suffix:
        type: string
    type: object
  github_com_copolio_namegpt_pkg_dto.GenerateDomainNameResult:
    properties:
      domainName:
        type: string
      info:
        items:
          $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto.DomainInfo'
        type: array
    type: object
  github_com_copolio_namegpt_pkg_dto.GenerateDomainNames:
    properties:
      keyword:
        type: string
      user:
        type: string
    required:
    - keyword
    type: object
  github_com_copolio_namegpt_pkg_dto.RecommendDomainNames:
    properties:
      description:
        type: string
      previousResults:
        items:
          type: string
        type: array
      userId:
        type: string
    required:
    - description
    type: object
info:
  contact: {}
paths:
  /api/v1/domains/recommendations:
    post:
      consumes:
      - application/json
      parameters:
      - description: Generate domain name recommendation
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto.RecommendDomainNames'
      produces:
      - application/json
      responses:
        "201":
          description: domain
          schema:
            items:
              type: string
            type: array
      summary: Generates domain names in server sent event.
      tags:
      - v1
  /api/v1/domains/similar-names:
    post:
      parameters:
      - description: Generate similar domain name
        in: body
        name: q
        required: true
        schema:
          $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto.GenerateDomainNames'
      produces:
      - application/json
      responses:
        "200":
          description: domain names
          schema:
            items:
              $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto.GenerateDomainNameResult'
            type: array
      summary: Get similar domain names given input
      tags:
      - v1
swagger: "2.0"
