definitions:
  github_com_copolio_namegpt_internal_namegpt_entity.DomainName:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      queryID:
        type: integer
      updatedAt:
        type: string
    type: object
  github_com_copolio_namegpt_internal_namegpt_entity.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  github_com_copolio_namegpt_pkg_dto_request.CreateUser:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
paths:
  /v0/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Pong!
      tags:
      - v0
  /v0/users:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create user request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto_request.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            $ref: '#/definitions/github_com_copolio_namegpt_internal_namegpt_entity.User'
      summary: Creates a user.
      tags:
      - v0
  /v0/users/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Username
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            $ref: '#/definitions/github_com_copolio_namegpt_internal_namegpt_entity.User'
      summary: Gets a user info by name.
      tags:
      - v0
  /v1/search:
    get:
      parameters:
      - in: query
        name: keyword
        required: true
        type: string
      - in: query
        name: user
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: domain names
          schema:
            items:
              $ref: '#/definitions/github_com_copolio_namegpt_internal_namegpt_entity.DomainName'
            type: array
      summary: Get similar domain names given input
      tags:
      - v1
swagger: "2.0"
