definitions:
  github_com_copolio_namegpt_internal_namegpt_entity.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  github_com_copolio_namegpt_pkg_dto_request.CreateUser:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
paths:
  /v0/ping:
    get:
      consumes:
      - application/json
      description: This is detail Description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: This is simple Summary.
  /v1/users:
    post:
      consumes:
      - application/json
      description: Creates a user in database.
      parameters:
      - description: Create user request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_copolio_namegpt_pkg_dto_request.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            $ref: '#/definitions/github_com_copolio_namegpt_internal_namegpt_entity.User'
      summary: Creates a user.
  /v1/users/{name}:
    get:
      consumes:
      - application/json
      description: Gets a user info from database.
      parameters:
      - description: Username
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: user
          schema:
            $ref: '#/definitions/github_com_copolio_namegpt_internal_namegpt_entity.User'
      summary: Gets a user info by name.
swagger: "2.0"
